language: python
cache: pip
python: 2.7.10
install:
- pip install -r requirements.txt
script:
- python main.py -d
after_success:
- chmod u+x compress.sh && ./compress.sh
deploy:
  provider: s3
  bucket: www.fanzhang.me
  region: us-east-1
  skip_cleanup: true
  default_text_charset: utf-8
  cache_control: max-age=43200
  local-dir: output
  detect_encoding: true
  access_key_id: AKIAJM53XXEQFM4UKQUA
  secret_access_key:
    secure: 0maelQNIAOTJCkIU9on18ui3LtgxQsYz2B8g0wRHg44uwXSLH+iuAcLHRGZjgH/dsA6Qo1kidd+L93SQT29sUKFr+PiGpFY28DiMGqSOAbc+Efi4XqKUgLbjfZ5Qlux7rishNluup7fQfrJADy8+6IyQImR9WizuspgL8mdxJNwJf79h6s2BaMJJdVFh5r8l6rxawFJaxa5hT8NpjruJwk/gZ0uVgIaFX4QtRfNwcEBHWMwG+CrpKlME9370AVhEQKIPp0SruRI/uIMKLM/8sPNmSIpjYJzVh34KjKmqfTDBXI3nDQmXRfToF3zIR9eWZzc2SPns0KZy9Zb6nNiHMZuYNAY/M/2CleJUAP+srO80QSTLUJXDcIA/PCqgYcxXXRx5lzLkHxSZsmWmQZ/0zc9zEYszh8mALx8Usw5Agnz+wnoicymt/7xjDvaO7mxDykCFWdLeRxpXwKsLhB7ZKzW5mtze+1dq2NbkQqHi0qsuAgHgMBC6p9PkFiERSPkhNx9SbF9+BG8ZS0eqTO3a02kn9wxnQlq6jId8u5GWqSjazDKwvEASVW0A9HECByUkB0IzPxrxBn/XWCyEhiaSoLKXT9JNFFLVJPdYVvN+PXWLvXO754hsuMpDnbaTELmGwEuNfW6r41YX/FVSqphKIEg3oOYbWXREa9nu/2ButE0=
notifications:
  email:
    recipients:
    - bl4ck5unxx@gmail.com
    on_failure: always
