# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fan Zhang
email: bl4ck5unxx@gmail.com
description: Fan's Webpage
baseurl: "" # the subpath of your site, e.g. /blog

exclude: [compass, semantic, semantic.json, node_modules]
# Build settings
excerpt_separator: "\n\n"
highlighter: rouge

gem: [compass]
